# Imports

In [28]:
import os
import re

import pandas as pd
import polars as pl

GENE_SYMBOL_PATTERN = re.compile(r"gene_name=([\w\d]+)")
pd.options.display.max_columns = 50

# Filenames

In [2]:
bhf_fasta = "/home/ec2-user/s3/seanome-kmerseek/applications/botryllus/botryllus-proteins/bhf.fa"
human_fasta = "/home/ec2-user/s3/seanome-kmerseek/applications/botryllus/data/gencode/v38/gencode.v38.basic.annotation.protein.fa"

# Sigfiles
bhf_sig = f"{bhf_fasta}.hp.k24.scale5.zip"
human_singleton_sig = f"{human_fasta}.hp.k24.scale5.singleton.zip"
human_aggregated_sig = f"{human_fasta}.hp.k24.scale5.aggregated.zip"

bhf_kmers_csv = f"{bhf_sig}.kmers.csv"
human_aggregated_kmers_csv = f"{human_aggregated_sig}.kmers.csv"

outdir = "/home/ec2-user/s3/seanome-kmerseek/applications/botryllus/adhoc-analysis/2025-02-feb-yc-demo/"
fastgather_results = os.path.join(
    outdir, "bhf-human-gencode-v38-fastgather-results.csv"
)
multisearch_results = os.path.join(
    outdir, "bhf-human-gencode-v38-multisearch-results.csv"
)

# Read results

## Fastgather

In [29]:
fastgather = pd.read_csv(fastgather_results)
# Remove whitespace
fastgather["query_name"] = fastgather["query_name"].str.strip()
fastgather["gene_name"] = fastgather["match_name"].str.extract(GENE_SYMBOL_PATTERN)
print(fastgather.shape)
fastgather.head()

(18, 32)

,intersect_bp,f_orig_query,f_match,f_unique_to_query,f_unique_weighted,average_abund,median_abund,std_abund,match_filename,match_name,match_md5,f_match_orig,unique_intersect_bp,gather_result_rank,remaining_bp,query_filename,query_name,query_md5,query_bp,ksize,moltype,scaled,query_n_hashes,query_abundance,query_containment_ani,match_containment_ani,average_containment_ani,max_containment_ani,n_unique_weighted_found,sum_weighted_found,total_weighted_hashes,gene_name
0,15,0.075,0.032258,0.075,0.075,1.0,1.0,0.0,signatures/a1cd3306c355c8cfda8b72a095baa71a.si...,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,a1cd3306c355c8cfda8b72a095baa71a,0.032258,15,0,185,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.964664,0.953425,0.959044,0.964664,3,3,40,RNMT
1,10,0.050,0.004505,0.050,0.050,1.0,1.0,0.0,signatures/205dc5fc750d18e05661a4ba4f3037ee.si...,ENST00000502264.5 gene_id=ENSG00000006283.18;t...,205dc5fc750d18e05661a4ba4f3037ee,0.004505,10,1,175,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.959246,0.927709,0.943478,0.959246,2,5,40,CACNA1G
2,10,0.050,0.003591,0.050,0.050,1.0,1.0,0.0,signatures/cd920c9ea15076edab81069f4a0c00b5.si...,ENST00000369577.8 gene_id=ENSG00000188994.13;t...,cd920c9ea15076edab81069f4a0c00b5,0.003591,10,2,165,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.959246,0.924792,0.942019,0.959246,2,7,40,ZNF292
3,10,0.050,0.013333,0.050,0.050,1.0,1.0,0.0,signatures/00b584b913d3c2c380350578acd69259.si...,ENST00000216832.9 gene_id=ENSG00000100941.9;tr...,00b584b913d3c2c380350578acd69259,0.013333,10,3,155,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.959246,0.941797,0.950522,0.959246,2,9,40,PNN
4,10,0.050,0.013158,0.050,0.050,1.0,1.0,0.0,signatures/27f2e1feebdda6a6db42e87a45278f1a_4....,ENST00000252519.8 gene_id=ENSG00000130234.13;t...,27f2e1feebdda6a6db42e87a45278f1a,0.013158,10,4,145,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.959246,0.941624,0.950435,0.959246,2,11,40,ACE2

## Multisearch

In [4]:
multisearch = pd.read_csv(multisearch_results)
print(multisearch.shape)
multisearch.head()

FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/s3/seanome-kmerseek/applications/botryllus/adhoc-analysis/2025-02-feb-yc-demo/bhf-human-gencode-v38-multisearch-results.csv'

# Read kmer csvs

### Read BHF Kmer csv

In [5]:
bhf_kmers = pd.read_csv(bhf_kmers_csv)
print(bhf_kmers.shape)
bhf_kmers.head()

(40, 6)

,kmer_in_sequence,kmer_in_alphabet,hashval,start,read_name,filename
0,VHDTEQLLAQGHHEEETECGKYGK,hppppphhhphpppppppphphhp,1036020595944595459,1,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
1,TEQLLAQGHHEEETECGKYGKLPE,ppphhhphpppppppphphhphhp,2993707203445337902,4,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
2,EQLLAQGHHEEETECGKYGKLPEK,pphhhphpppppppphphhphhpp,973051056292048589,5,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
3,ETECGKYGKLPEKGSECKKHGIFC,pppphphhphhpphpppppphhhp,385192726330471768,16,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
4,KYGKLPEKGSECKKHGIFCRILTA,phhphhpphpppppphhhpphhph,1194029314525711201,21,BHF,/home/ec2-user/s3/seanome-kmerseek/application...

## Get human kmers

### Read Human Kmer csv

In [7]:
human_aggregated_kmers = pl.scan_csv(human_aggregated_kmers_csv)
# print(human_aggregated_kmers.shape)
# human_aggregated_kmers.head()
human_aggregated_kmers

In [9]:
human_aggregated_kmers_fastgather = human_aggregated_kmers.filter(
    pl.col("read_name").is_in(fastgather["match_name"])
).collect()
human_aggregated_kmers_fastgather

shape: (4_990, 6)
┌──────────────────┬─────────────────┬─────────────────┬───────┬─────────────────┬─────────────────┐
│ kmer_in_sequence ┆ kmer_in_alphabe ┆ hashval         ┆ start ┆ read_name       ┆ filename        │
│ ---              ┆ t               ┆ ---             ┆ ---   ┆ ---             ┆ ---             │
│ str              ┆ ---             ┆ i64             ┆ i64   ┆ str             ┆ str             │
│                  ┆ str             ┆                 ┆       ┆                 ┆                 │
╞══════════════════╪═════════════════╪═════════════════╪═══════╪═════════════════╪═════════════════╡
│ ELKEDKMLEVHFVGDD ┆ phpppphhphphhhp ┆ 178418087566324 ┆ 4     ┆ ENST00000234296 ┆ /home/ec2-user/ │
│ DVLNHILD         ┆ pphhpphhp       ┆ 2866            ┆       ┆ .7              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ VHFVGDDDVLNHILDR ┆ hphhhppphhpphhp ┆ 114108946868021 ┆ 13    ┆ ENST00000234296 ┆ /home/ec2-user/ │
│ EGGAKLKK         ┆ pphhhphpp       ┆ 6797            ┆       ┆ .7              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ HFVGDDDVLNHILDRE ┆ phhhppphhpphhpp ┆ 103119199926371 ┆ 14    ┆ ENST00000234296 ┆ /home/ec2-user/ │
│ GGAKLKKE         ┆ phhhphppp       ┆ 1520            ┆       ┆ .7              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ GDDDVLNHILDREGGA ┆ hppphhpphhppphh ┆ 112498263262281 ┆ 17    ┆ ENST00000234296 ┆ /home/ec2-user/ │
│ KLKKERAQ         ┆ hphpppphp       ┆ 121             ┆       ┆ .7              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ LNHILDREGGAKLKKE ┆ hpphhppphhhphpp ┆ 120699926955084 ┆ 22    ┆ ENST00000234296 ┆ /home/ec2-user/ │
│ RAQLLVNP         ┆ pphphhhph       ┆ 0444            ┆       ┆ .7              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ …                ┆ …               ┆ …               ┆ …     ┆ …               ┆ …               │
│ RKKKNKARSGENPYAS ┆ pppppphpphpphhh ┆ 635786569948001 ┆ 767   ┆ ENST00000252519 ┆ /home/ec2-user/ │
│ IDISKGEN         ┆ phphpphpp       ┆ 256             ┆       ┆ .8              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ RSGENPYASIDISKGE ┆ pphpphhhphphpph ┆ 654435353136923 ┆ 774   ┆ ENST00000252519 ┆ /home/ec2-user/ │
│ NNPGFQNT         ┆ ppphhhppp       ┆ 231             ┆       ┆ .8              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ GENPYASIDISKGENN ┆ hpphhhphphpphpp ┆ 970548289930977 ┆ 776   ┆ ENST00000252519 ┆ /home/ec2-user/ │
│ PGFQNTDD         ┆ phhhppppp       ┆ 118             ┆       ┆ .8              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ NPYASIDISKGENNPG ┆ phhhphphpphppph ┆ 264435352302010 ┆ 778   ┆ ENST00000252519 ┆ /home/ec2-user/ │
│ FQNTDDVQ         ┆ hhppppphp       ┆ 9479            ┆       ┆ .8              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
│ ASIDISKGENNPGFQN ┆ hphphpphppphhhp ┆ 364783526328852 ┆ 781   ┆ ENST00000252519 ┆ /home/ec2-user/ │
│ TDDVQTSF         ┆ pppphppph       ┆ 8052            ┆       ┆ .8              ┆ s3/seanome-kmer │
│                  ┆                 ┆                 ┆       ┆ gene_id=ENSG…   ┆ …               │
└──────────────────┴─────────────────┴─────────────────┴───────┴─────────────────┴─────────────────┘

In [10]:
human_aggregated_kmers_fastgather_pd = human_aggregated_kmers_fastgather.to_pandas()
human_aggregated_kmers_fastgather_pd.head()

,kmer_in_sequence,kmer_in_alphabet,hashval,start,read_name,filename
0,ELKEDKMLEVHFVGDDDVLNHILD,phpppphhphphhhppphhpphhp,1784180875663242866,4,ENST00000234296.7 gene_id=ENSG00000115942.9;tr...,/home/ec2-user/s3/seanome-kmerseek/application...
1,VHFVGDDDVLNHILDREGGAKLKK,hphhhppphhpphhppphhhphpp,1141089468680216797,13,ENST00000234296.7 gene_id=ENSG00000115942.9;tr...,/home/ec2-user/s3/seanome-kmerseek/application...
2,HFVGDDDVLNHILDREGGAKLKKE,phhhppphhpphhppphhhphppp,1031191999263711520,14,ENST00000234296.7 gene_id=ENSG00000115942.9;tr...,/home/ec2-user/s3/seanome-kmerseek/application...
3,GDDDVLNHILDREGGAKLKKERAQ,hppphhpphhppphhhphpppphp,112498263262281121,17,ENST00000234296.7 gene_id=ENSG00000115942.9;tr...,/home/ec2-user/s3/seanome-kmerseek/application...
4,LNHILDREGGAKLKKERAQLLVNP,hpphhppphhhphpppphphhhph,1206999269550840444,22,ENST00000234296.7 gene_id=ENSG00000115942.9;tr...,/home/ec2-user/s3/seanome-kmerseek/application...

# Join fastgather, multisearch results with kmers

## Fastgather with bhf

In [15]:
bhf_kmers.head()

,kmer_in_sequence,kmer_in_alphabet,hashval,start,read_name,filename
0,VHDTEQLLAQGHHEEETECGKYGK,hppppphhhphpppppppphphhp,1036020595944595459,1,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
1,TEQLLAQGHHEEETECGKYGKLPE,ppphhhphpppppppphphhphhp,2993707203445337902,4,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
2,EQLLAQGHHEEETECGKYGKLPEK,pphhhphpppppppphphhphhpp,973051056292048589,5,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
3,ETECGKYGKLPEKGSECKKHGIFC,pppphphhphhpphpppppphhhp,385192726330471768,16,BHF,/home/ec2-user/s3/seanome-kmerseek/application...
4,KYGKLPEKGSECKKHGIFCRILTA,phhphhpphpppppphhhpphhph,1194029314525711201,21,BHF,/home/ec2-user/s3/seanome-kmerseek/application...

## Merge query and database kmers

In [13]:
merge_on = ["kmer_in_alphabet", "hashval"]

bhf_human_kmers = bhf_kmers.merge(
    human_aggregated_kmers_fastgather_pd,
    left_on=merge_on,
    right_on=merge_on,
    suffixes=("_query", "_match"),
)
bhf_human_kmers.head()

,kmer_in_sequence_query,kmer_in_alphabet,hashval,start_query,read_name_query,filename_query,kmer_in_sequence_match,start_match,read_name_match,filename_match
0,ETECGKYGKLPEKGSECKKHGIFC,pppphphhphhpphpppppphhhp,385192726330471768,16,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,TESQLTFVQALKDLKKSNTKAYGE,1267,ENST00000681847.1 gene_id=ENSG00000118492.18;t...,/home/ec2-user/s3/seanome-kmerseek/application...
1,KYGKLPEKGSECKKHGIFCRILTA,phhphhpphpppppphhhpphhph,1194029314525711201,21,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,SVFTGASKFRCKDCSAAYDTLVEL,192,ENST00000322038.5 gene_id=ENSG00000179981.11;t...,/home/ec2-user/s3/seanome-kmerseek/application...
2,EKGSECKKHGIFCRILTALHLKKR,pphpppppphhhpphhphhphppp,723610543814117516,27,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,RRWSDKSKSVLARNALSGPDWESD,726,ENST00000547771.6 gene_id=ENSG00000166268.11;t...,/home/ec2-user/s3/seanome-kmerseek/application...
3,ECKKHGIFCRILTALHLKKRRTEH,ppppphhhpphhphhphppppppp,2309144907826564485,31,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,SDESTLIFDQIPEVITVSKTSEDT,517,ENST00000512590.6 gene_id=ENSG00000038427.16;t...,/home/ec2-user/s3/seanome-kmerseek/application...
4,CRILTALHLKKRRTEHDHQKLLSE,pphhphhphppppppppppphhpp,1452226584929511062,39,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,RRLGRPPKITTTNENQKTNTVAKQ,606,ENST00000369577.8 gene_id=ENSG00000188994.13;t...,/home/ec2-user/s3/seanome-kmerseek/application...

## Merge fastgather with query+database k-mers

In [22]:
merge_fastgather_on = ["match_name", "query_name", "query_filename"]
merge_kmers_on = ["read_name_match", "read_name_query", "filename_query"]

In [30]:
# fastgather[merge_fastgather_on].head().values

In [31]:
# bhf_human_kmers[merge_kmers_on].head().values

In [32]:
fastgather_kmers = fastgather.merge(
    bhf_human_kmers,
    left_on=merge_fastgather_on,
    right_on=merge_kmers_on,
)
print(fastgather_kmers.shape)
fastgather_kmers.head()

(25, 42)

,intersect_bp,f_orig_query,f_match,f_unique_to_query,f_unique_weighted,average_abund,median_abund,std_abund,match_filename,match_name,match_md5,f_match_orig,unique_intersect_bp,gather_result_rank,remaining_bp,query_filename,query_name,query_md5,query_bp,ksize,moltype,scaled,query_n_hashes,query_abundance,query_containment_ani,match_containment_ani,average_containment_ani,max_containment_ani,n_unique_weighted_found,sum_weighted_found,total_weighted_hashes,gene_name,kmer_in_sequence_query,kmer_in_alphabet,hashval,start_query,read_name_query,filename_query,kmer_in_sequence_match,start_match,read_name_match,filename_match
0,15,0.075,0.032258,0.075,0.075,1.0,1.0,0.0,signatures/a1cd3306c355c8cfda8b72a095baa71a.si...,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,a1cd3306c355c8cfda8b72a095baa71a,0.032258,15,0,185,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.964664,0.953425,0.959044,0.964664,3,3,40,RNMT,LHLKKRRTEHDHQKLLSESQEHLD,hphppppppppppphhpppppphp,1686103030246593445,45,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,AEGNSKKRKRETEDVPKDKSSTGD,97,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,/home/ec2-user/s3/seanome-kmerseek/application...
1,15,0.075,0.032258,0.075,0.075,1.0,1.0,0.0,signatures/a1cd3306c355c8cfda8b72a095baa71a.si...,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,a1cd3306c355c8cfda8b72a095baa71a,0.032258,15,0,185,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.964664,0.953425,0.959044,0.964664,3,3,40,RNMT,KKRRTEHDHQKLLSESQEHLDAST,ppppppppppphhpppppphphpp,1936090226493821700,48,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,NSKKRKRETEDVPKDKSSTGDGTQ,100,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,/home/ec2-user/s3/seanome-kmerseek/application...
2,15,0.075,0.032258,0.075,0.075,1.0,1.0,0.0,signatures/a1cd3306c355c8cfda8b72a095baa71a.si...,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,a1cd3306c355c8cfda8b72a095baa71a,0.032258,15,0,185,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.964664,0.953425,0.959044,0.964664,3,3,40,RNMT,KRRTEHDHQKLLSESQEHLDASTK,pppppppppphhpppppphphppp,3529800228978433891,49,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,SKKRKRETEDVPKDKSSTGDGTQN,101,ENST00000592764.5 gene_id=ENSG00000101654.18;t...,/home/ec2-user/s3/seanome-kmerseek/application...
3,10,0.050,0.004505,0.050,0.050,1.0,1.0,0.0,signatures/205dc5fc750d18e05661a4ba4f3037ee.si...,ENST00000502264.5 gene_id=ENSG00000006283.18;t...,205dc5fc750d18e05661a4ba4f3037ee,0.004505,10,1,175,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.959246,0.927709,0.943478,0.959246,2,5,40,CACNA1G,SLCSVDLIPVDIEFWDMENEPVDQ,phpphphhhhphphhphppphhpp,2199858909433221760,128,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,SLEHPTIPLAEMEALSLTSEIVSE,1898,ENST00000502264.5 gene_id=ENSG00000006283.18;t...,/home/ec2-user/s3/seanome-kmerseek/application...
4,10,0.050,0.004505,0.050,0.050,1.0,1.0,0.0,signatures/205dc5fc750d18e05661a4ba4f3037ee.si...,ENST00000502264.5 gene_id=ENSG00000006283.18;t...,205dc5fc750d18e05661a4ba4f3037ee,0.004505,10,1,175,/home/ec2-user/s3/seanome-kmerseek/application...,BHF,3ac7314af031571512a844a7b18bd75e,200,72,hp,5,40,True,0.959246,0.927709,0.943478,0.959246,2,5,40,CACNA1G,LCSVDLIPVDIEFWDMENEPVDQL,hpphphhhhphphhphppphhpph,2633737169387093056,129,BHF,/home/ec2-user/s3/seanome-kmerseek/application...,LEHPTIPLAEMEALSLTSEIVSEP,1899,ENST00000502264.5 gene_id=ENSG00000006283.18;t...,/home/ec2-user/s3/seanome-kmerseek/application...

In [39]:
fastgather_kmers = fastgather_kmers.sort_values("start_query")

In [42]:
for (match_name, query_name), df in fastgather_kmers.groupby(
    ["gene_name", "query_name"], sort=False
):
    print(f"\n--- {match_name} matched to {query_name} ---")

    for i, row in df.iterrows():
        print(f"-\nmatch: {row.kmer_in_sequence_match} (starts @ {row.start_match})")
        print(f"hp   : {row.kmer_in_alphabet}")
        print(f"query: {row.kmer_in_sequence_query} (starts @ {row.start_query})")

    if match_name == "ZNF292":
        break

--- ADGB matched to BHF ---
-
match: TESQLTFVQALKDLKKSNTKAYGE (starts @ 1267)
hp   : pppphphhphhpphpppppphhhp
query: ETECGKYGKLPEKGSECKKHGIFC (starts @ 16)

--- TSHZ1 matched to BHF ---
-
match: SVFTGASKFRCKDCSAAYDTLVEL (starts @ 192)
hp   : phhphhpphpppppphhhpphhph
query: KYGKLPEKGSECKKHGIFCRILTA (starts @ 21)

--- MYRFL matched to BHF ---
-
match: RRWSDKSKSVLARNALSGPDWESD (starts @ 726)
hp   : pphpppppphhhpphhphhphppp
query: EKGSECKKHGIFCRILTALHLKKR (starts @ 27)

--- VCAN matched to BHF ---
-
match: SDESTLIFDQIPEVITVSKTSEDT (starts @ 517)
hp   : ppppphhhpphhphhphppppppp
query: ECKKHGIFCRILTALHLKKRRTEH (starts @ 31)

--- ZNF292 matched to BHF ---
-
match: RRLGRPPKITTTNENQKTNTVAKQ (starts @ 606)
hp   : pphhphhphppppppppppphhpp
query: CRILTALHLKKRRTEHDHQKLLSE (starts @ 39)
-
match: GRPPKITTTNENQKTNTVAKQEQR (starts @ 609)
hp   : hphhphppppppppppphhppppp
query: LTALHLKKRRTEHDHQKLLSESQE (starts @ 42)

In [51]:
def single_stitch_together_kmers(kmers: pd.Series(str), i_kmers: pd.Series(int)):
    stitched = ""
    for i, (i_kmer, kmer) in enumerate(zip(i_kmers, kmers)):
        if i == 0:
            stitched = kmer
            prev_i_kmer = i_kmer
        else:
            kmer_slice = i_kmer - prev_i_kmer
            stitched += kmer[-kmer_slice:]
    return stitched


single_stitch_together_kmers(df.kmer_in_sequence_query, df.start_query)

'CRILTALHLKKRRTEHDHQKLLSESQE'

In [59]:
def stitch_kmers_in_query_match_pair(
    df,
    kmer_match="kmer_in_sequence_match",
    kmer_alphabet="kmer_in_alphabet",
    kmer_query="kmer_in_sequence_query",
    start_match="start_match",
    start_query="start_query",
):
    df = df.sort_values(start_query)

    query = single_stitch_together_kmers(df[kmer_query], df[start_match])
    alphabet = single_stitch_together_kmers(df[kmer_alphabet], df[start_query])
    match = single_stitch_together_kmers(df[kmer_match], df[start_match])

    # All these lengths should be the same -> if not, something whent wrong
    assert len(query) == len(alphabet)
    assert len(alphabet) == len(match)

    length = len(query)

    match_start = df[start_match].min()
    query_start = df[start_query].min()
    match_end = match_start + length
    query_end = query_start + length

    to_print = f"query: {query}\n" f"alpha: {alphabet}\n" f"match: {match}"
    stitched_output = pd.Series(
        dict(
            query_start=query_start,
            query_end=query_end,
            query=query,
            match_start=match_start,
            match_end=match_end,
            match=match,
            combined=to_print,
        )
    )
    return stitched_output


stitch_kmers_in_query_match_pair(df)

query_start                                                   39
query_end                                                     66
query                                CRILTALHLKKRRTEHDHQKLLSESQE
match_start                                                  606
match_end                                                    633
match                                RRLGRPPKITTTNENQKTNTVAKQEQR
combined       query: CRILTALHLKKRRTEHDHQKLLSESQE\nalpha: pph...
dtype: object

In [63]:
fastgather_kmers.groupby("gene_name").apply(
    stitch_kmers_in_query_match_pair
).sort_values(["query_start", "query_end"])

/tmp/ipykernel_17302/1854749356.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fastgather_kmers.groupby("gene_name").apply(

,query_start,query_end,query,match_start,match_end,match,combined
gene_name,,,,,,,
ADGB,16,40,ETECGKYGKLPEKGSECKKHGIFC,1267,1291,TESQLTFVQALKDLKKSNTKAYGE,query: ETECGKYGKLPEKGSECKKHGIFC\nalpha: pppphp...
TSHZ1,21,45,KYGKLPEKGSECKKHGIFCRILTA,192,216,SVFTGASKFRCKDCSAAYDTLVEL,query: KYGKLPEKGSECKKHGIFCRILTA\nalpha: phhphh...
MYRFL,27,51,EKGSECKKHGIFCRILTALHLKKR,726,750,RRWSDKSKSVLARNALSGPDWESD,query: EKGSECKKHGIFCRILTALHLKKR\nalpha: pphppp...
VCAN,31,55,ECKKHGIFCRILTALHLKKRRTEH,517,541,SDESTLIFDQIPEVITVSKTSEDT,query: ECKKHGIFCRILTALHLKKRRTEH\nalpha: ppppph...
ZNF292,39,66,CRILTALHLKKRRTEHDHQKLLSESQE,606,633,RRLGRPPKITTTNENQKTNTVAKQEQR,query: CRILTALHLKKRRTEHDHQKLLSESQE\nalpha: pph...
RNMT,45,76,LHLKKRRTEHDHQKLLSESQEHLDASTASTK,97,128,AEGNSKKRKRETEDVPKDKSSTGDGTQGTQN,query: LHLKKRRTEHDHQKLLSESQEHLDASTASTK\nalpha:...
ZNF713,64,88,QEHLDASTKKTKKKAKKDKRKNKP,104,128,ENRPEIKKSTTSQNISDENQTHEM,query: QEHLDASTKKTKKKAKKDKRKNKP\nalpha: ppphph...
PNN,74,99,TKKKAKKDKRKNKPPKKDSETSKPA,645,670,HRRSVDRKRRDTSGLERSHKSSKGG,query: TKKKAKKDKRKNKPPKKDSETSKPA\nalpha: pppph...
ACE2,96,123,KPAQTTISRLPSNRNNNNANSFATTYE,97,124,QALQQNGSSVLSEDKSKRLNTILNTMS,query: KPAQTTISRLPSNRNNNNANSFATTYE\nalpha: phh...
DNAH3,115,139,NSFATTYEKFDNDSLCSVDLIPVD,329,353,HSVYRSAKKWNEEHLHTVNPMMLR,query: NSFATTYEKFDNDSLCSVDLIPVD\nalpha: pphhpp...
CACNA1G,128,153,SLCSVDLIPVDIEFWDMENEPVDQL,1898,1923,SLEHPTIPLAEMEALSLTSEIVSEP,query: SLCSVDLIPVDIEFWDMENEPVDQL\nalpha: phpph...
JMJD1C,142,166,WDMENEPVDQLPHEILESVHMYGD,592,616,PTINTHPLTSGPHHAVHHPHLLPT,query: WDMENEPVDQLPHEILESVHMYGD\nalpha: hphppp...
SFI1,156,180,ILESVHMYGDDRFGERLIDRAQNK,107,131,FPSKARFYYEQRLLRKVFEEWKEE,query: ILESVHMYGDDRFGERLIDRAQNK\nalpha: hhpphp...
ORC2,168,193,FGERLIDRAQNKYAPLDEKQRSESH,157,182,FLSTAPRSLRKRLIVPRSHSDSESE,query: FGERLIDRAQNKYAPLDEKQRSESH\nalpha: hhpph...
TRAPPC10,173,197,IDRAQNKYAPLDEKQRSESHGAGE,831,855,LCQAESRAVVYSNTREQSSEAALR,query: IDRAQNKYAPLDEKQRSESHGAGE\nalpha: hpphpp...
PCDHGA9,186,210,KQRSESHGAGEYLKHQWKGQGAKK,479,503,DSNENSRVIYSLAEDTIQGSPLST,query: KQRSESHGAGEYLKHQWKGQGAKK\nalpha: pppppp...
ABCC5,194,218,AGEYLKHQWKGQGAKKARKRIRTV,958,982,PMKFFDTTPTGRILNRFSKDMDEV,query: AGEYLKHQWKGQGAKKARKRIRTV\nalpha: hhphhp...
NDNF,211,235,RKRIRTVMKATWQSLQAGARSQTA,118,142,NEEGTELFSYKGNDVEYFISSSSP,query: RKRIRTVMKATWQSLQAGARSQTA\nalpha: ppphpp...