In [1]:
!  sourmash scripts manysearch  --help

== This is sourmash version 4.8.14. ==
== Please cite Irber et. al (2024), doi:10.21105/joss.06830. ==

usage:  manysearch [-h] [-q] [-d] -o OUTPUT [-t THRESHOLD] [-k KSIZE]
                   [-s SCALED] [-m {DNA,protein,dayhoff,hp,skipm1n3,skipm2n3}]
                   [-c CORES] [-P] [-N] [--ignore-abundance] [-A]
                   query_paths against_paths

search many metagenomes for contained genomes

positional arguments:
  query_paths           input file of sketches
  against_paths         input file of sketches

options:
  -h, --help            show this help message and exit
  -q, --quiet           suppress non-error output
  -d, --debug           provide debugging output
  -o OUTPUT, --output OUTPUT
                        CSV output file for matches
  -t THRESHOLD, --threshold THRESHOLD
                        containment threshold for reporting matches (default:
                        0.01)
  -k KSIZE, --ksize KSIZE
                        k-mer size at which to select sketches
  -s SCALED, --scaled SCALED
                        scaled factor at which to do comparisons
  -m {DNA,protein,dayhoff,hp,skipm1n3,skipm2n3}, --moltype {DNA,protein,dayhoff,hp,skipm1n3,skipm2n3}
                        molecule type: DNA, protein, dayhoff, hp, or skipmer
                        (skipm1n3 or skipm2n3); default DNA
  -c CORES, --cores CORES
                        number of cores to use (default is all available)
  -P, --pretty-print    display results after search finishes (default: True)
  -N, --no-pretty-print
                        do not display results (e.g. for large output)
  --ignore-abundance    do not do expensive abundance calculations
  -A, --output-all-comparisons
                        ignore threshold and output all comparisons; against a
                        RocksDB database, this will only output comparisons
                        with some overlap

In [8]:
%%file manysearch_botryllus_query
/home/ec2-user/s3/seanome-kmerseek/applications/botryllus/botryllus-proteins/bhf.fa.hp.k24.scaled5.sig.zip

Writing manysearch_botryllus_query

In [10]:
%%file manysearch_human_against
/home/ec2-user/uniprotkb_taxonomy_name_Human_AND_revie_2025_02_06.fasta.gz.hp.k24.scaled5.sig.zip

Writing manysearch_human_against

In [11]:
%%time

!  sourmash scripts manysearch \
    --threshold 0 \
    --ksize 24 \
    --moltype hp \
    --scaled 5 \
    --output 2025-02-06--botryllus-human-uniprot-manysearch.csv \
    manysearch_botryllus_query \
    manysearch_human_against

== This is sourmash version 4.8.14. ==
== Please cite Irber et. al (2024), doi:10.21105/joss.06830. ==

=> sourmash_plugin_branchwater 0.9.14.dev0; cite Irber et al., doi: 10.1101/2022.11.02.514947

ksize: 24 / scaled: 5 / moltype: hp / threshold: 0.0
searching all sketches in 'manysearch_botryllus_query' against 'manysearch_human_against' using 8 threads
selection scaled: Some(5)
Reading query(s) from: 'manysearch_botryllus_query'
FAILED to load as JSON files; falling back to general recursive
Loaded 1 query signature(s)
Reading search(s) from: 'manysearch_human_against'
FAILED to load as JSON files; falling back to general recursive
Loaded 46080 search signature(s)
Processed 1000 search sigs
Processed 2000 search sigs
Processed 3000 search sigs
Processed 4000 search sigs
Processed 5000 search sigs
Processed 6000 search sigs
Processed 7000 search sigs
Processed 8000 search sigs
Processed 9000 search sigs
Processed 10000 search sigs
Processed 11000 search sigs
Processed 12000 search sigs
Processed 13000 search sigs
Processed 14000 search sigs
Processed 15000 search sigs
Processed 16000 search sigs
Processed 17000 search sigs
Processed 18000 search sigs
Processed 19000 search sigs
Processed 20000 search sigs
Processed 21000 search sigs
Processed 22000 search sigs
Processed 23000 search sigs
Processed 24000 search sigs
Processed 25000 search sigs
Processed 26000 search sigs
Processed 27000 search sigs
Processed 28000 search sigs
Processed 29000 search sigs
Processed 30000 search sigs
Processed 31000 search sigs
Processed 32000 search sigs
Processed 33000 search sigs
Processed 34000 search sigs
Processed 35000 search sigs
Processed 36000 search sigs
Processed 37000 search sigs
Processed 38000 search sigs
Processed 39000 search sigs
Processed 40000 search sigs
Processed 41000 search sigs
Processed 42000 search sigs
Processed 43000 search sigs
Processed 44000 search sigs
Processed 45000 search sigs
Processed 46000 search sigs
DONE. Processed 46080 search sigs
...manysearch is done! results in '2025-02-06--botryllus-human-uniprot-manysearch.csv'

query             p_genome avg_abund   p_metag   metagenome name
--------          -------- ---------   -------   ---------------
BHF                  2.5%     1.0       0.4%     sp|Q96J65|MRP9_HU
BHF                  2.5%     1.0       0.4%     sp|A8K8P3|SFI1_HU
BHF                  2.5%     1.0       1.9%     sp|P21739|V_PI4HA
BHF                  2.5%     1.0       1.3%     sp|Q8N859|ZN713_H
BHF                  2.5%     1.0       1.9%     sp|O00124|UBXN8_H
BHF                  5.0%     1.0       0.7%     sp|Q96T23|RSF1_HU
BHF                  2.5%     1.0       2.1%     sp|P28278|GL_HHV2
BHF                  2.5%     1.0       0.3%     sp|P33527-2|MRP1_
BHF                  2.5%     1.0       0.3%     sp|P33527-3|MRP1_
BHF                  2.5%     1.0       0.3%     sp|P33527-4|MRP1_
BHF                  2.5%     1.0       0.4%     sp|P33527-5|MRP1_
BHF                  2.5%     1.0       0.4%     sp|P33527-6|MRP1_
BHF                  2.5%     1.0       0.4%     sp|P33527-7|MRP1_
BHF                  2.5%     1.0       0.4%     sp|P33527-8|MRP1_
BHF                  2.5%     1.0       0.3%     sp|P33527-9|MRP1_
BHF                  2.5%     1.0       4.5%     sp|Q8TE69|EOLA1_H
BHF                  2.5%     1.0       0.4%     sp|Q92610|ZN592_H
BHF                  5.0%     1.0       0.7%     sp|P52347|MCP_HHV
BHF                  2.5%     1.0       0.6%     sp|Q8TD57-2|DYH3_
BHF                  2.5%     1.0       0.3%     sp|Q8TD57-3|DYH3_
BHF                  2.5%     1.0       2.9%     sp|O15347|HMGB3_H
BHF                  2.5%     1.0       5.6%     sp|Q8TE69-2|EOLA1
BHF                  2.5%     1.0       0.4%     sp|O15440|MRP5_HU
BHF                  7.5%     1.0       3.5%     sp|O43148|MCES_HU
BHF                  5.0%     1.0       1.3%     sp|Q9BYF1|ACE2_HU
BHF                  2.5%     1.0       0.5%     sp|Q9Y5G4|PCDG9_H
BHF                  2.5%     1.0       0.2%     sp|O43497|CAC1G_H
BHF                  5.0%     1.0       0.5%     sp|O43497-10|CAC1
BHF                  2.5%     1.0       0.2%     sp|O43497-20|CAC1
BHF                  2.5%     1.0       0.2%     sp|O43497-33|CAC1
BHF                  2.5%     1.0       0.2%     sp|O43497-4|CAC1G
BHF                  2.5%     1.0       1.2%     sp|Q13098-5|CSN1_
BHF                  2.5%     1.0       1.1%     sp|Q13098-7|CSN1_
BHF                  2.5%     1.0       0.9%     sp|Q2M329|CF184_H
BHF                  5.0%     1.0       0.4%     sp|O60281|ZN292_H
BHF                  5.0%     1.0       1.3%     sp|Q9H307|PININ_H
BHF                  2.5%     1.0       1.1%     sp|O60669|MOT2_HU
BHF                  2.5%     1.0       0.6%     sp|Q96J65-2|MRP9_
BHF                  5.0%     1.0       1.1%     sp|Q9HBG6-10|IF12
BHF                  2.5%     1.0       0.6%     sp|Q96J65-5|MRP9_
BHF                  2.5%     1.0       0.8%     sp|Q9HC62|SENP2_H
BHF                  2.5%     1.0       1.0%     sp|P06162|PHOSP_P
BHF                  2.5%     1.0       0.4%     sp|P09853|RIR1_HH
BHF                  2.5%     1.0       2.0%     sp|P20896|GLYC_HR
BHF                  2.5%     1.0       2.0%     sp|P23041|GLYC_HR
BHF                  2.5%     1.0       0.5%     sp|Q9NRE2|TSH2_HU
BHF                  2.5%     1.0       0.3%     sp|Q15652-2|JHD2C
BHF                  2.5%     1.0       0.2%     sp|Q15652-3|JHD2C
BHF                  2.5%     1.0       0.9%     sp|Q05134|VE1_HPV
BHF                  5.0%     1.0       0.7%     sp|Q96T23-2|RSF1_
BHF                  5.0%     1.0       0.9%     sp|Q96T23-3|RSF1_
BHF                  2.5%     1.0       0.4%     sp|O15440-5|MRP5_
BHF                  7.5%     1.0       3.2%     sp|O43148-2|MCES_
BHF                  2.5%     1.0       0.4%     sp|A8K8P3-2|SFI1_
BHF                  2.5%     1.0       2.2%     sp|O00124-2|UBXN8
BHF                  2.5%     1.0       2.3%     sp|O00124-3|UBXN8
BHF                  2.5%     1.0       0.4%     sp|P89462|RIR1_HH
BHF                  2.5%     1.0       0.5%     sp|Q6ZSZ6-2|TSH1_
BHF                  5.0%     1.0       0.4%     sp|O60281-2|ZN292
BHF                  2.5%     1.0       0.4%     sp|P08543|RIR1_HH
BHF                  2.5%     1.0       1.2%     sp|Q13098|CSN1_HU
BHF                  5.0%     1.0       1.9%     sp|P12645|BMP3_HU
BHF                  5.0%     1.0       1.6%     sp|Q13416|ORC2_HU
BHF                  2.5%     1.0       0.8%     sp|Q9HC62-2|SENP2
BHF                  2.5%     1.0       0.1%     sp|P13611|CSPG2_H
BHF                  2.5%     1.0       2.4%     sp|P20896-2|GLYC_
BHF                  2.5%     1.0       0.6%     sp|Q6VY07|PACS1_H
BHF                  2.5%     1.0       2.4%     sp|P23041-2|GLYC_
BHF                  2.5%     1.0       0.5%     sp|Q9NRE2-2|TSH2_
BHF                  2.5%     1.0       0.5%     sp|Q6ZSZ6|TSH1_HU
BHF                  2.5%     1.0       0.3%     sp|P13611-3|CSPG2
BHF                  2.5%     1.0       0.1%     sp|P13611-5|CSPG2
BHF                  2.5%     1.0       0.5%     sp|Q6VY07-2|PACS1
BHF                  2.5%     1.0       0.2%     sp|P25391|LAMA1_H
BHF                  2.5%     1.0       1.0%     sp|Q14554|PDIA5_H
BHF                  2.5%     1.0       0.4%     sp|Q14562|DHX8_HU
BHF                  5.0%     1.0       0.6%     sp|Q8NDM7|CFA43_H
BHF                  2.5%     1.0       0.3%     sp|P33527|MRP1_HU
BHF                  2.5%     1.0       1.2%     sp|P22044|PHOSP_P
BHF                  2.5%     1.0       1.0%     sp|Q8TB73|NDNF_HU
BHF                  2.5%     1.0       0.2%     sp|Q15652|JHD2C_H
BHF                  2.5%     1.0       0.1%     sp|Q8TD57|DYH3_HU
BHF                  2.5%     1.0       0.5%     sp|Q63HK5|TSH3_HU
BHF                  2.5%     1.0       0.4%     sp|P48553|TPC10_H
BHF                  2.5%     1.0       0.6%     sp|Q9Y5G4-2|PCDG9
BHF                  2.5%     1.0       0.5%     sp|Q93033|IGSF2_H
BHF                  2.5%     1.0       0.3%     sp|Q8N7X0|ADGB_HU
CPU times: user 73.4 ms, sys: 26.8 ms, total: 100 ms
Wall time: 8.47 s

In [13]:
import pandas as pd

manysearch = pd.read_csv('2025-02-06--botryllus-human-uniprot-manysearch.csv')
manysearch

,query_name,query_md5,match_name,containment,intersect_hashes,ksize,scaled,moltype,match_md5,jaccard,max_containment,average_abund,median_abund,std_abund,query_containment_ani,match_containment_ani,average_containment_ani,max_containment_ani,n_weighted_found,total_weighted_hashes
0,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q96J65|MRP9_HUMAN ATP-binding cassette sub-...,0.025,1,72,5,hp,3bff913d2efdb2d09931eab82f10aeb9,0.003610,0.025,1.0,1.0,0.0,0.950056,0.926813,0.938434,0.950056,1,238
1,BHF,3ac7314af031571512a844a7b18bd75e,sp|A8K8P3|SFI1_HUMAN Protein SFI1 homolog OS=H...,0.025,1,72,5,hp,9ef2acc860a537e324762d1a2e2fbf75,0.003534,0.025,1.0,1.0,0.0,0.950056,0.926492,0.938274,0.950056,1,244
2,BHF,3ac7314af031571512a844a7b18bd75e,sp|P21739|V_PI4HA Non-structural protein V OS=...,0.025,1,72,5,hp,a9e32a12c2fcc364dcb18d5a3a2c3638,0.010753,0.025,1.0,1.0,0.0,0.950056,0.946104,0.948080,0.950056,1,54
3,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q8N859|ZN713_HUMAN Zinc finger protein 713 ...,0.025,1,72,5,hp,91e33bd99845ef4db1e30e85e23c166e,0.008475,0.025,1.0,1.0,0.0,0.950056,0.941118,0.945587,0.950056,1,79
4,BHF,3ac7314af031571512a844a7b18bd75e,sp|O00124|UBXN8_HUMAN UBX domain-containing pr...,0.025,1,72,5,hp,20feba26fc2c509234ab07d1ec3d16ab,0.010989,0.025,1.0,1.0,0.0,0.950056,0.946600,0.948328,0.950056,1,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q63HK5|TSH3_HUMAN Teashirt homolog 3 OS=Hom...,0.025,1,72,5,hp,6078c10a7cdb837be06fe5c0112017cd,0.003968,0.025,1.0,1.0,0.0,0.950056,0.928242,0.939149,0.950056,1,213
83,BHF,3ac7314af031571512a844a7b18bd75e,sp|P48553|TPC10_HUMAN Trafficking protein part...,0.025,1,72,5,hp,c6c2848e7fbfb31ac4c8e7e25129ffc5,0.003559,0.025,1.0,1.0,0.0,0.950056,0.926598,0.938327,0.950056,1,242
84,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q9Y5G4-2|PCDG9_HUMAN Isoform 2 of Protocadh...,0.025,1,72,5,hp,facd04236e54b361238093305ddd63bf,0.004785,0.025,1.0,1.0,0.0,0.950056,0.931154,0.940605,0.950056,1,170
85,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q93033|IGSF2_HUMAN Immunoglobulin superfami...,0.025,1,72,5,hp,0f96e9068996ec4a0e1fe923711b42d6,0.004167,0.025,1.0,1.0,0.0,0.950056,0.928990,0.939523,0.950056,1,201
86,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q8N7X0|ADGB_HUMAN Androglobin OS=Homo sapie...,0.025,1,72,5,hp,76206b51f917acb0cd711c4abe970fa1,0.002747,0.025,1.0,1.0,0.0,0.950056,0.922811,0.936433,0.950056,1,325

In [14]:
manysearch.loc[manysearch.match_name.str.contains('Zinc')]

,query_name,query_md5,match_name,containment,intersect_hashes,ksize,scaled,moltype,match_md5,jaccard,max_containment,average_abund,median_abund,std_abund,query_containment_ani,match_containment_ani,average_containment_ani,max_containment_ani,n_weighted_found,total_weighted_hashes
3,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q8N859|ZN713_HUMAN Zinc finger protein 713 ...,0.025,1,72,5,hp,91e33bd99845ef4db1e30e85e23c166e,0.008475,0.025,1.0,1.0,0.0,0.950056,0.941118,0.945587,0.950056,1,79
16,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q92610|ZN592_HUMAN Zinc finger protein 592 ...,0.025,1,72,5,hp,85bcff3423734035cda4f42324d2af6f,0.003663,0.025,1.0,1.0,0.0,0.950056,0.927031,0.938543,0.950056,1,234
34,BHF,3ac7314af031571512a844a7b18bd75e,sp|O60281|ZN292_HUMAN Zinc finger protein 292 ...,0.050,2,72,5,hp,cd920c9ea15076edab81069f4a0c00b5,0.003361,0.050,1.0,1.0,0.0,0.959246,0.924792,0.942019,0.959246,2,557
58,BHF,3ac7314af031571512a844a7b18bd75e,sp|O60281-2|ZN292_HUMAN Isoform 2 of Zinc fing...,0.050,2,72,5,hp,58d375adbb7a65500549b607e068332c,0.003490,0.050,1.0,1.0,0.0,0.959246,0.925310,0.942278,0.959246,2,535

In [16]:
manysearch.loc[manysearch.match_name.str.contains('TSHZ')]

,query_name,query_md5,match_name,containment,intersect_hashes,ksize,scaled,moltype,match_md5,jaccard,max_containment,average_abund,median_abund,std_abund,query_containment_ani,match_containment_ani,average_containment_ani,max_containment_ani,n_weighted_found,total_weighted_hashes
45,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q9NRE2|TSH2_HUMAN Teashirt homolog 2 OS=Hom...,0.025,1,72,5,hp,aaae1d4c3dc0dabaff0ee22312f166a9,0.004149,0.025,1.0,1.0,0.0,0.950056,0.928926,0.939491,0.950056,1,202
57,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q6ZSZ6-2|TSH1_HUMAN Isoform 2 of Teashirt h...,0.025,1,72,5,hp,24d6324c2b8516ef0f684685bbce37d2,0.004016,0.025,1.0,1.0,0.0,0.950056,0.928425,0.939241,0.950056,1,210
68,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q9NRE2-2|TSH2_HUMAN Isoform 2 of Teashirt h...,0.025,1,72,5,hp,962b12a1b431434a742108bd12e5b823,0.004149,0.025,1.0,1.0,0.0,0.950056,0.928926,0.939491,0.950056,1,202
69,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q6ZSZ6|TSH1_HUMAN Teashirt homolog 1 OS=Hom...,0.025,1,72,5,hp,1c090fd5cc151c99139524bfbc98cd9c,0.003953,0.025,1.0,1.0,0.0,0.950056,0.928182,0.939119,0.950056,1,214
82,BHF,3ac7314af031571512a844a7b18bd75e,sp|Q63HK5|TSH3_HUMAN Teashirt homolog 3 OS=Hom...,0.025,1,72,5,hp,6078c10a7cdb837be06fe5c0112017cd,0.003968,0.025,1.0,1.0,0.0,0.950056,0.928242,0.939149,0.950056,1,213